services:
  - type: web
    name: ai-resume-analyzer
    env: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
